//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public @event()
        {
            this.registrationevent = new HashSet<registrationevent>();
            this.registrationevent1 = new HashSet<registrationevent>();
        }
    
        public string EventId { get; set; }
        public string EventName { get; set; }
        public string EventTypeId { get; set; }
        public sbyte MarathonId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<short> MaxParticipants { get; set; }
    
        public virtual eventtype eventtype { get; set; }
        public virtual marathon marathon { get; set; }
        public virtual eventtype eventtype1 { get; set; }
        public virtual marathon marathon1 { get; set; }
        public virtual ICollection<registrationevent> registrationevent { get; set; }
        public virtual ICollection<registrationevent> registrationevent1 { get; set; }
    }
}
