//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class marathon
    {
        public marathon()
        {
            this.@event = new HashSet<@event>();
            this.event1 = new HashSet<@event>();
        }
    
        public sbyte MarathonId { get; set; }
        public string MarathonName { get; set; }
        public string CityName { get; set; }
        public string CountryCode { get; set; }
        public Nullable<short> YearHeld { get; set; }
    
        public virtual country country { get; set; }
        public virtual country country1 { get; set; }
        public virtual ICollection<@event> @event { get; set; }
        public virtual ICollection<@event> event1 { get; set; }
    }
}
