//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.user = new HashSet<user>();
            this.user1 = new HashSet<user>();
        }
    
        public string RoleId { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<user> user { get; set; }
        public virtual ICollection<user> user1 { get; set; }
    }
}
